name: Build Containerimage

on:
  push:
    tags:
      - '*.*.*'
  schedule:
    - cron: '55 10 * * *'

jobs:
  push_to_registry:
    name: Push detour-proxy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build
        env:
          DOCKER_ORG: ${{ vars.DOCKER_ORG }}
          DOCKER_REG: ${{ vars.DOCKER_REG }}
          DOCKER_TAG: ${{ steps.vars.outputs.tag }}
          DOCKER_LTG: latest
        run: docker build . --file Dockerfile --tag ${DOCKER_ORG}/${DOCKER_REG}:${DOCKER_TAG} --tag ${{ vars.DOCKER_ORG }}/${DOCKER_REG}:${DOCKER_LTG}

      - name: push
        env:
          DOCKER_ORG: ${{ vars.DOCKER_ORG }}
          DOCKER_REG: ${{ vars.DOCKER_REG }}
        run: docker image push --all-tags ${DOCKER_ORG}/${DOCKER_REG}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        env:
          DOCKER_ORG: ${{ vars.DOCKER_ORG }}
          DOCKER_REG: ${{ vars.DOCKER_REG }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${DOCKER_ORG}/${DOCKER_REG}
